# Generated by Django 4.2.17 on 2024-12-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan_simulator", "0004_alter_user_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"managed": False},
        ),
        migrations.RemoveField(
            model_name="loanapplication",
            name="application_date",
        ),
        migrations.RemoveField(
            model_name="loanapplication",
            name="loan_details",
        ),
        migrations.RemoveField(
            model_name="loanapplication",
            name="loan_simulation",
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="application_status",
            field=models.CharField(
                choices=[
                    ("accept", "Accepted"),
                    ("interview", "Interview"),
                    ("reject", "Rejected"),
                ],
                default="accept",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="credit_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="loan_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="loan_duration",
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="monthly_expenses",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="monthly_income",
            field=models.IntegerField(default=0),
        ),
    ]
