# Generated by Django 4.2.17 on 2024-12-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan_simulator", "0005_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanapplication",
            name="username",
            field=models.CharField(default="default_username", max_length=255),
        ),
    ]
