# Generated by Django 4.2.17 on 2024-12-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_income",
                    models.IntegerField(verbose_name="Monthly income (€)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interest_rate", models.FloatField(verbose_name="Interest rate (%)")),
                ("total_repayment", models.FloatField(verbose_name="Total repayment")),
                (
                    "monthly_payment",
                    models.IntegerField(verbose_name="Monthly payment (€)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanSimulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="Amount (€)")),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duration (months)"
                    ),
                ),
                (
                    "desired_monthly_payment",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Desired monthly payment (€)",
                    ),
                ),
            ],
        ),
    ]
