# Generated by Django 4.2.17 on 2024-12-27 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoanDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interest_rate", models.FloatField(verbose_name="Interest rate (%)")),
                (
                    "total_repayment",
                    models.FloatField(verbose_name="Total repayment (€)"),
                ),
                (
                    "monthly_payment",
                    models.IntegerField(verbose_name="Monthly payment (€)"),
                ),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LoanSimulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="Amount (€)")),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duration (months)"
                    ),
                ),
                (
                    "desired_monthly_payment",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Desired monthly payment (€)",
                    ),
                ),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("face_id", models.CharField(max_length=255)),
                ("user_type", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "User",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        verbose_name="User requesting the loan application (authenticated user)"
                    ),
                ),
                (
                    "monthly_income",
                    models.IntegerField(verbose_name="Monthly income (€)"),
                ),
                (
                    "monthly_expenses",
                    models.IntegerField(verbose_name="Monthly expenses (€)"),
                ),
                ("amount", models.IntegerField(verbose_name="Amount (€)")),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duration (months)"
                    ),
                ),
                (
                    "desired_monthly_payment",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Desired monthly payment (€)",
                    ),
                ),
                (
                    "credit_score",
                    models.IntegerField(
                        verbose_name="Credit score (calculated by model)"
                    ),
                ),
                (
                    "application_status",
                    models.CharField(
                        choices=[
                            ("accept", "Accepted"),
                            ("interview", "Interview"),
                            ("reject", "Rejected"),
                        ],
                        max_length=9,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LoanEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, null=True, verbose_name="Annotations"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accept", "Accepted"),
                            ("interview", "Interview"),
                            ("reject", "Rejected"),
                            ("unevaluated", "Not yet evaluated"),
                        ],
                        default="unevaluated",
                        max_length=11,
                    ),
                ),
                (
                    "officer",
                    models.CharField(
                        max_length=255,
                        verbose_name="Officer evaluating the loan application",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="When was the evaluation record created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Last time the evaluation was updated",
                    ),
                ),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.loanapplication",
                    ),
                ),
            ],
        ),
    ]
