# Generated by Django 4.2.17 on 2024-12-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanevaluation",
            name="timeslot",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Interview Timeslot"
            ),
        ),
    ]
