# Generated by Django 4.2.17 on 2024-12-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_user"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="User",
        ),
    ]
