# Generated by Django 4.2.17 on 2024-12-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_loanapplication_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loandetails",
            old_name="api",
            new_name="loan_simulation",
        ),
    ]
